x-env-file: &env-file
  - path: .env
    required: false

x-app-environment: &app-environment
  IS_DEBUG: "false"
  POSTGRES_HOST: pg
  POSTGRES_PORT: "5432"
  POSTGRES_DB: ${POSTGRES_DB:-tarot}
  POSTGRES_USER: ${POSTGRES_USER:-tarot}
  REDIS_HOST: redis
  REDIS_PORT: "6379"

services:
  admin:
    container_name: admin-tarot
    build:
      dockerfile: Dockerfile
    env_file: *env-file
    environment: *app-environment
    command: sh -c "alembic upgrade head && python -m bot.run_admin"
    ports:
      - "8080:8080"
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped

  bot:
    container_name: bot-tarot
    build:
      dockerfile: Dockerfile
    env_file: *env-file
    environment: *app-environment
    command: python -m bot.run_bot
    depends_on:
      pg:
        condition: service_healthy
      admin:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped

  pg:
    container_name: pg-tarot
    image: postgres:16
    env_file: *env-file
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tarot}
      POSTGRES_USER: ${POSTGRES_USER:-tarot}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 5s
      interval: 1m
      timeout: 3s
      retries: 5
    restart: unless-stopped

  redis:
    container_name: redis-tarot
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      interval: 1m
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
