x-app-environment: &app-environment
  IS_DEBUG: "false"
  BOT_TOKEN: ${BOT_TOKEN}
  ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  ADMIN_SECRET_KEY: ${ADMIN_SECRET_KEY}
  ADMIN_PORT: ${ADMIN_PORT:-8080}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST:-pg}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  LOG_LEVEL: ${LOG_LEVEL:-INFO}

services:
  admin:
    container_name: admin-tarot
    build:
      dockerfile: Dockerfile
    environment: *app-environment
    command: sh -c "alembic upgrade head && python -m bot.run_admin"
    ports:
      - "${ADMIN_PORT:-8080}:${ADMIN_PORT:-8080}"
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped

  bot:
    container_name: bot-tarot
    build:
      dockerfile: Dockerfile
    environment: *app-environment
    command: python -m bot.run_bot
    depends_on:
      pg:
        condition: service_healthy
      admin:
        condition: service_started
    restart: unless-stopped

  pg:
    container_name: pg-tarot
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      start_period: 5s
      interval: 1m
      timeout: 3s
      retries: 5
    restart: unless-stopped
